// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: users.proto

package users_pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _users_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on LoginRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *LoginRequest) Validate() error {
	if m == nil {
		return nil
	}

	if !_LoginRequest_PhoneNumber_Pattern.MatchString(m.GetPhoneNumber()) {
		return LoginRequestValidationError{
			field:  "PhoneNumber",
			reason: "value does not match regex pattern \"^1[3|5|7|8][0-9]{9}$\"",
		}
	}

	if utf8.RuneCountInString(m.GetCaptcha()) != 6 {
		return LoginRequestValidationError{
			field:  "Captcha",
			reason: "value length must be 6 runes",
		}

	}

	return nil
}

// LoginRequestValidationError is the validation error returned by
// LoginRequest.Validate if the designated constraints aren't met.
type LoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginRequestValidationError) ErrorName() string { return "LoginRequestValidationError" }

// Error satisfies the builtin error interface
func (e LoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginRequestValidationError{}

var _LoginRequest_PhoneNumber_Pattern = regexp.MustCompile("^1[3|5|7|8][0-9]{9}$")

// Validate checks the field values on LoginResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *LoginResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Token

	return nil
}

// LoginResponseValidationError is the validation error returned by
// LoginResponse.Validate if the designated constraints aren't met.
type LoginResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginResponseValidationError) ErrorName() string { return "LoginResponseValidationError" }

// Error satisfies the builtin error interface
func (e LoginResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginResponseValidationError{}

// Validate checks the field values on GetCaptchaRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GetCaptchaRequest) Validate() error {
	if m == nil {
		return nil
	}

	if !_GetCaptchaRequest_PhoneNumber_Pattern.MatchString(m.GetPhoneNumber()) {
		return GetCaptchaRequestValidationError{
			field:  "PhoneNumber",
			reason: "value does not match regex pattern \"^1[3|5|7|8][0-9]{9}$\"",
		}
	}

	return nil
}

// GetCaptchaRequestValidationError is the validation error returned by
// GetCaptchaRequest.Validate if the designated constraints aren't met.
type GetCaptchaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCaptchaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCaptchaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCaptchaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCaptchaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCaptchaRequestValidationError) ErrorName() string {
	return "GetCaptchaRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCaptchaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCaptchaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCaptchaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCaptchaRequestValidationError{}

var _GetCaptchaRequest_PhoneNumber_Pattern = regexp.MustCompile("^1[3|5|7|8][0-9]{9}$")

// Validate checks the field values on VerifyCaptchaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *VerifyCaptchaRequest) Validate() error {
	if m == nil {
		return nil
	}

	if !_VerifyCaptchaRequest_PhoneNumber_Pattern.MatchString(m.GetPhoneNumber()) {
		return VerifyCaptchaRequestValidationError{
			field:  "PhoneNumber",
			reason: "value does not match regex pattern \"^1[3|5|7|8][0-9]{9}$\"",
		}
	}

	if utf8.RuneCountInString(m.GetCaptcha()) != 6 {
		return VerifyCaptchaRequestValidationError{
			field:  "Captcha",
			reason: "value length must be 6 runes",
		}

	}

	return nil
}

// VerifyCaptchaRequestValidationError is the validation error returned by
// VerifyCaptchaRequest.Validate if the designated constraints aren't met.
type VerifyCaptchaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VerifyCaptchaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VerifyCaptchaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VerifyCaptchaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VerifyCaptchaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VerifyCaptchaRequestValidationError) ErrorName() string {
	return "VerifyCaptchaRequestValidationError"
}

// Error satisfies the builtin error interface
func (e VerifyCaptchaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVerifyCaptchaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VerifyCaptchaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VerifyCaptchaRequestValidationError{}

var _VerifyCaptchaRequest_PhoneNumber_Pattern = regexp.MustCompile("^1[3|5|7|8][0-9]{9}$")

// Validate checks the field values on VerifyCaptchaResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *VerifyCaptchaResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Verified

	return nil
}

// VerifyCaptchaResponseValidationError is the validation error returned by
// VerifyCaptchaResponse.Validate if the designated constraints aren't met.
type VerifyCaptchaResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VerifyCaptchaResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VerifyCaptchaResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VerifyCaptchaResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VerifyCaptchaResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VerifyCaptchaResponseValidationError) ErrorName() string {
	return "VerifyCaptchaResponseValidationError"
}

// Error satisfies the builtin error interface
func (e VerifyCaptchaResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVerifyCaptchaResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VerifyCaptchaResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VerifyCaptchaResponseValidationError{}

// Validate checks the field values on User with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *User) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for PhoneNumber

	// no validation rules for LastLoginAt

	// no validation rules for LastLoginIp

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	// no validation rules for Avatar

	// no validation rules for Nickname

	return nil
}

// UserValidationError is the validation error returned by User.Validate if the
// designated constraints aren't met.
type UserValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserValidationError) ErrorName() string { return "UserValidationError" }

// Error satisfies the builtin error interface
func (e UserValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUser.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserValidationError{}

// Validate checks the field values on UpdateUserInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdateUserInfoRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Nickname

	return nil
}

// UpdateUserInfoRequestValidationError is the validation error returned by
// UpdateUserInfoRequest.Validate if the designated constraints aren't met.
type UpdateUserInfoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserInfoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserInfoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserInfoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserInfoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserInfoRequestValidationError) ErrorName() string {
	return "UpdateUserInfoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateUserInfoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateUserInfoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateUserInfoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserInfoRequestValidationError{}

// Validate checks the field values on UpdateUserInfoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdateUserInfoResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Nickname

	return nil
}

// UpdateUserInfoResponseValidationError is the validation error returned by
// UpdateUserInfoResponse.Validate if the designated constraints aren't met.
type UpdateUserInfoResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserInfoResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserInfoResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserInfoResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserInfoResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserInfoResponseValidationError) ErrorName() string {
	return "UpdateUserInfoResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateUserInfoResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateUserInfoResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateUserInfoResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserInfoResponseValidationError{}

// Validate checks the field values on UploadAvatarRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UploadAvatarRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Avatar

	return nil
}

// UploadAvatarRequestValidationError is the validation error returned by
// UploadAvatarRequest.Validate if the designated constraints aren't met.
type UploadAvatarRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadAvatarRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadAvatarRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadAvatarRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadAvatarRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadAvatarRequestValidationError) ErrorName() string {
	return "UploadAvatarRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UploadAvatarRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadAvatarRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadAvatarRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadAvatarRequestValidationError{}

// Validate checks the field values on UploadAvatarResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UploadAvatarResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ImageUrl

	return nil
}

// UploadAvatarResponseValidationError is the validation error returned by
// UploadAvatarResponse.Validate if the designated constraints aren't met.
type UploadAvatarResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadAvatarResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadAvatarResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadAvatarResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadAvatarResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadAvatarResponseValidationError) ErrorName() string {
	return "UploadAvatarResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UploadAvatarResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadAvatarResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadAvatarResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadAvatarResponseValidationError{}
